// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCD1ytjYLWX-VML387YO9FX3k66ejjzR0',
    appId: '1:966451654816:web:2fbc5d87785ad47a5019c5',
    messagingSenderId: '966451654816',
    projectId: 'catalogprjk',
    authDomain: 'catalogprjk.firebaseapp.com',
    storageBucket: 'catalogprjk.firebasestorage.app',
    measurementId: 'G-PLJ4G6G2VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ8DUHgSVKFlK5ihheP5SrXHluBBXBmVA',
    appId: '1:966451654816:android:ac1a730d3045f0455019c5',
    messagingSenderId: '966451654816',
    projectId: 'catalogprjk',
    storageBucket: 'catalogprjk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCD1ytjYLWX-VML387YO9FX3k66ejjzR0',
    appId: '1:966451654816:web:591b7a7848f160ba5019c5',
    messagingSenderId: '966451654816',
    projectId: 'catalogprjk',
    authDomain: 'catalogprjk.firebaseapp.com',
    storageBucket: 'catalogprjk.firebasestorage.app',
    measurementId: 'G-MVFRBCMB90',
  );
}
